apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saumyadb
  name: saumyadb
  namespace: saumya-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saumyadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saumyadb
    spec:
      volumes: #to create volume
      - name: saumyadbvol
        hostPath: #pod will take space from Minion node
         path: /data/saumyadb
         type: DirectoryOrCreate
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom: #to call env variable from configMap
        - configMapRef:
           name: saumya-db-config
        env: #calling env variale from secret
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
            name: saumyadb-sec
            key: db_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: saumyadb-sec
            key: root_pass
        resources: {}
        volumeMounts: #to mount the volume created above
        - name: saumyadbvol
          mountPath: /var/lib/mysql/
status: {}
