apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: saumyadblb
  name: saumyadblb
  namespace: saumya-project
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: saumyadb
  type: ClusterIP
status:
  loadBalancer: {}
