apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saumyawebapp
  name: saumyawebapp
  namespace: saumya-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saumyawebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saumyawebapp
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        envFrom: #calling docker image env variables
        - configMapRef:
           name: saumyaweb-config
        env: #to call password from secret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: #taking data from secret
            secretKeyRef:
             name: saumyadb-sec
             key: db_pass
        resources: {}
status: {}
